- name: nginx configuration
  template:
    src: mysite.j2
    dest: /etc/nginx/sites-enabled/mysite
  notify: restart nginx
  tags: configuration

- name: remove defaults
  file: path="/etc/nginx/sites-enabled/default" state=absent
  tags: configuration
