- name: "Install common packages"
  apt: update_cache=yes name={{ item }} state=present
  with_items:
    #- python3-pip
    - python-pip
    - python-dev 
    - libmysqlclient-dev
    - unzip
    - pydf
    - tree
  tags: installation
